@startuml

hide circle
' left to right direction
skinparam roundcorner 0
skinparam shadowing false
skinparam linetype ortho
skinparam FontSize 18
skinparam defaultFontName JetBrains Mono
' scale 1.5

skinparam class {
    BackgroundColor white
    BorderThickness 1.0
    FontStyle bold
}

!procedure column($name, $name_size, $type, $type_size, $constraints="")
    !while %strlen($name) < $name_size
        !$name = $name + " "
    !endwhile
    !while %strlen($type) < $type_size
        !$type = $type + " "
    !endwhile
    $name  $type  $constraints
!endprocedure

entity book {
    column(id,               16, INTEGER,         13, PK)
    --
    column(title,            16, 'VARCHAR(256)',  13, NN)
    column(description,      16, 'VARCHAR(1024)', 13)
    column(isbn,             16, ISBN,            13)
    column(publication_date, 16, DATE,            13)
    column(page_count,       16, SMALLINT,        13)
    column(publisher_id,     16, INTEGER,         13, 'FK NN')
    column(series_id,        16, INTEGER,         13)
    column(comment,          16, 'VARCHAR(1024)', 13)
}

entity genre {
    column(id,          11, SMALLINT,        13, PK)
    --
    column(name,        11, 'VARCHAR(64)',   13, 'UQ NN')
    column(description, 11, 'VARCHAR(512)',  13)
    column(comment,     11, 'VARCHAR(1024)', 13)
}

entity publisher {
    column(id,              15, INTEGER,         13, PK)
    --
    column(name,            15, 'VARCHAR(128)',  13, NN)
    column(description,     15, 'VARCHAR(1024)', 13)
    column(foundation_date, 15, DATE,            13)
    column(comment,         15, 'VARCHAR(1024)', 13)
}

entity book_genre {
    column(book_id,  8, INTEGER,  8, 'PK FK')
    column(genre_id, 8, SMALLINT, 8, 'PK FK')
    --
}

entity book_copy {
    column(id,               16, INTEGER,         13, PK)
    --
    column(book_id,          16, INTEGER,         13, 'FK NN')
    column(receipt_date,     16, DATE,            13, NN)
    column(write_off_date,   16, DATE,            13)
    column(write_off_reason, 16, 'VARCHAR(256)',  13)
    column(rack_number,      16, SMALLINT,        13)
    column(shelf_number,     16, SMALLINT,        13)
    column(comment,          16, 'VARCHAR(1024)', 13)
}

entity person {
    column(id,         10, INTEGER,         13, PK)
    --
    column(first_name, 10, 'VARCHAR(50)',   13, NN)
    column(last_name,  10, 'VARCHAR(50)',   13)
    column(patronymic, 10, 'VARCHAR(50)',   13)
    column(about,      10, 'VARCHAR(1024)', 13)
    column(birth_date, 10, DATE,            13)
    column(death_date, 10, DATE,            13)
    column(comment,    10, 'VARCHAR(1024)', 13)
}

entity participant_type {
    column(id,      7, TINYINT,         13, PK)
    --
    column(name,    7, 'VARCHAR(64)',   13, 'UQ NN')
    column(comment, 7, 'VARCHAR(1024)', 13)
}

entity book_participant {
    column(book_id,   9, INTEGER, 7, 'PK FK')
    column(person_id, 9, INTEGER, 7, 'PK FK')
    --
    column(type_id,   9, TINYINT, 7, 'FK NN')
}

entity reader_category {
    column(id,          11, SMALLINT,         13, PK)
    --
    column(name,        11, 'VARCHAR(64)',  13, 'UQ NN')
    column(description, 11, 'VARCHAR(256)', 13)
    column(comment,     11, 'VARCHAR(1024)', 13)
}

entity waitlist {
    column(id,               16, INTEGER,         13, PK)
    --
    column(book_id,          16, INTEGER,         13, 'NN')
    column(reader_id,        16, INTEGER,         13, 'FK NN')
    column(requested_amount, 16, SMALLINT,        13, NN)
    column(received_amount,  16, SMALLINT,        13, NN)
    column(start_date,       16, DATETIME,        13, NN)
    column(end_date,         16, DATETIME,        13)
    column(comment,          16, 'VARCHAR(1024)', 13)
}

entity checkout {
    column(id,           12, INTEGER,         13, PK)
    --
    column(start_date,   12, DATETIME,        13, NN)
    column(return_date,  12, DATETIME,        13)
    column(book_copy_id, 12, INTEGER,         13, 'FK NN')
    column(reader_id,    12, INTEGER,         13, 'FK NN')
    column(employee_id,  12, INTEGER,         13, 'FK NN')
    column(comment,      12, 'VARCHAR(1024)', 13)
}

entity book_series {
    column(id,          11, INTEGER,          13, PK)
    --
    column(name,        11, 'VARCHAR(256)',  13, NN)
    column(description, 11, 'VARCHAR(1024)', 13)
    column(comment,     11, 'VARCHAR(1024)', 13)
}

entity account {
    column(id,            13, INTEGER,        12, PK)
    --
    column(first_name,    13, 'VARCHAR(50)',  12, NN)
    column(last_name,     13, 'VARCHAR(50)',  12, NN)
    column(patronymic,    13, 'VARCHAR(50)',  12)
    column(birth_date,    13, DATE,           12, NN)
    column(email,         13, 'VARCHAR(320)', 12, 'UQ NN')
    column(phone_number,  13, 'VARCHAR(16)',  12, 'UQ NN')
    column(creation_date, 13, DATE,           12, NN)
}

entity reader {
    column(id,            13, INTEGER,         13, PK)
    --
    column(account_id,    13, INTEGER,         13, 'FK NN')
    column(ticket_number, 13, INTEGER,         13, 'UQ NN')
    column(category_id,   13, SMALLINT,        13, 'FK NN')
    column(comment,       13, 'VARCHAR(1024)', 13)
}

entity employee {
    column(id,              15, INTEGER,  8, PK)
    --
    column(account_id,      15, INTEGER,  8, 'FK NN')
    column(position_id,     15, SMALLINT, 8, 'FK NN')
    column(employment_date, 15, DATE,     8, NN)
    column(dismissal_date,  15, DATE,     8)
}

entity employee_position {
    column(id,       8, SMALLINT,      12, PK)
    --
    column(position, 8, 'VARCHAR(50)', 12, NN)
}

entity table_info {
    column(id,           12, SMALLINT,        13, PK)
    --
    column(number,       12, SMALLINT,        13, NN)
    column(has_computer, 12, BOOLEAN,         13, NN)
    column(comment,      12, 'VARCHAR(1024)', 13)
}

entity table_reservation {
    column(id,          11, INTEGER,         13, PK)
    --
    column(reader_id,   11, INTEGER,         13, 'FK NN')
    column(table_id,    11, SMALLINT,        13, 'FK NN')
    column(start_time,  11, DATETIME,        13, NN)
    column(end_time,    11, DATETIME,        13, NN)
    column(comment,     11, 'VARCHAR(1024)', 13)
}

entity audience {
    column(id,            13, SMALLINT,        13,  PK)
    --
    column(number,        13, INTEGER,         13, NN)
    column(seats_count,   13, SMALLINT,        13,  NN)
    column(has_projector, 13, BOOLEAN,         13, NN)
    column(comment,       13, 'VARCHAR(1024)', 13)
}

entity audience_reservation {
    column(id,                 18, INTEGER,         13, PK)
    --
    column(reader_id,          18, INTEGER,         13, 'FK NN')
    column(employee_id,        18, INTEGER,         13, 'FK NN')
    column(audience_id,        18, SMALLINT,        13, 'FK NN')
    column(event_id,           18, INTEGER,         13, 'FK NN')
    column(start_time,         18, DATETIME,        13, NN)
    column(end_time,           18, DATETIME,        13, NN)
    column(participants_count, 18, TINYINT,         13, NN)
    column(reason,             18, 'VARCHAR(128)',  13, NN)
    column(comment,            18, 'VARCHAR(1024)', 13)
}

entity event {
    column(id,          11, INTEGER,         13, PK)
    --
    column(name,        11, 'VARCHAR(64)',   13, NN)
    column(description, 11, 'VARCHAR(128)',  13, NN)
    column(start_date,  11, DATE,            13, NN)
    column(end_date,    11, DATE,            13, NN)
    column(reader_id,   11, INTEGER,         13, 'FK NN')
    column(comment,     11, 'VARCHAR(1024)', 13)
}

reader ||-up|| account
employee ||-up|| account
employee ||-up-|| employee_position

book ||-up-o{ book_genre
genre ||--o{ book_genre

book ||-left-o{ book_participant
person ||--o{ book_participant
participant_type ||--o{ book_participant

reader ||--o{ waitlist
book ||--o{ waitlist

publisher ||--o{ book

book_copy ||--o{ checkout
reader ||--o{ checkout
employee ||--o{ checkout

reader_category ||--o{ reader
book_series ||--o{ book
book ||-down-o{ book_copy

table_info ||-up-o{ table_reservation
reader ||--o{ table_reservation

audience ||-up-o{ audience_reservation
reader ||--o{ audience_reservation
employee ||--o{ audience_reservation
event ||--o{ audience_reservation

reader ||--o{ event

@enduml
